version: "3.8"

services:
  app:
    container_name: team_manager_app
    build:
      context: .
      dockerfile: src/TeamManager.Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      - "ASPNETCORE_URLS=http://+:80"
      - "database__connectionString=Host=postgres;Port=5432;Database=TeamManager;Username=postgres;Password=nicepassword"
    networks:
      - team_manager
  
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nicepassword
      POSTGRES_DB: Database
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - team_manager
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: nicepassword
    volumes:
      - pgadmin:/var/lib/pgadmin
        
  seq:
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    image: datalust/seq:latest

networks:
  team_manager:
    driver: bridge

volumes:
  postgres:
  pgadmin:
