version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nicepassword
      POSTGRES_DB: Database
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
#    networks:
#      - team_manager
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: nicepassword
    volumes:
      - pgadmin:/var/lib/pgadmin
#    networks:
#      - team_manager
        
  seq:
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    image: datalust/seq:latest
#    networks:
#      - team_manager

#networks:
#  team_manager:
#    name: team_manager
#    external: true

volumes:
  postgres:
  pgadmin:
